name: CI Pipeline 
on:
  push:
    branches:
      - master
  workflow_dispatch: 

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 pandas scikit-learn matplotlib seaborn dagshub
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Preprocess Data
        run: |
          echo "Generating dataset..."
          python src/preprocessing.py --input data_raw/data_telco.csv --output data_processed
          # Verify it worked
          ls -R data_processed

      - name: Train Model using MLflow Run
        env:
          # --- Credentials ---
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/SMSML_Afridho_Tavadhu.mlflow
          
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          # Debug Info
          echo "Workspace ada di: $GITHUB_WORKSPACE"
          # Jalankan MLflow
          mlflow run . --env-manager=local

      - name: Build & Push Docker Image
        env:
          # --- Credentials (Wajib Sama Persis) ---
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/SMSML_Afridho_Tavadhu.mlflow
        run: |
          echo "Mencari run_id.txt..."
          ls -la  
          
          if [ -f run_id.txt ]; then
             RUN_ID=$(cat run_id.txt)
             echo "✅ Found Run ID: $RUN_ID"
             
             # Build Docker
             mlflow models build-docker \
               -m "runs:/$RUN_ID/model" \
               -n "${{ secrets.DOCKER_USERNAME }}/smsml-submission:latest" \
               --enable-mlserver
               
             # Push ke Docker Hub
             docker push "${{ secrets.DOCKER_USERNAME }}/smsml-submission:latest"
             
          else
             echo "❌ Error: run_id.txt tidak ditemukan di $(pwd)"
             exit 1
          fi
